# Generated by Django 3.2.6 on 2021-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('user_identity', models.IntegerField()),
                ('github_url', models.CharField(max_length=200)),
                ('blog_url', models.CharField(max_length=200)),
                ('warning_cnt', models.IntegerField(default=0)),
                ('account_state', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
