# Generated by Django 3.2.6 on 2021-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=100)),
                ('user_job', models.CharField(max_length=15)),
                ('warning_cnt', models.IntegerField(default=0)),
                ('account_state', models.CharField(default='inactive', max_length=15)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
