# Generated by Django 3.2.6 on 2022-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(default='default.png', max_length=1024)),
            ],
            options={
                'db_table': 'profile_image',
                'managed': False,
            },
        ),
    ]
